require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'mercadoPagoCheckout' do
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false
  use_modular_headers!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'mercadoPagoCheckoutTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'mercadoPagoCheckout-tvOS' do
  # Pods for mercadoPagoCheckout-tvOS

  target 'mercadoPagoCheckout-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
